sudo: required
language: php
cache:
- vendor
php:
- '7.1'
before_script:
- composer install -o --ignore-platform-reqs
after_success:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- "./etc/deploy.sh"
- "./etc/deploy-docs.sh"
- "./etc/deploy-s3.sh"
install:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- travis_retry composer self-update && composer --version
script:
- "./etc/validate.sh"